# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

#target “OCRTest” do

platform :ios, '7.0'

pod 'SDWebImage', '~> 3.7'

pod 'MBProgressHUD', '~> 0.9'

pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git'

#end

#target "OCRTestTests" do

#end

